name: Release Charts

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"

      # - name: releaser
      #   run: |
      #     curl -L https://github.com/helm/chart-releaser/releases/download/v1.6.0/chart-releaser_1.6.0_linux_amd64.tar.gz > chart-releaser_1.6.0_linux_arm64.tar.gz
      #     tar -xzvf chart-releaser_1.6.0_linux_arm64.tar.gz
      #     ls -la
      #     rm -rf .cr-release-packages
      #     ./cr package charts/bind9
      #     ./cr upload --owner $GITHUB_REPOSITORY_OWNER --git-repo HelmCharts --token $CR_TOKEN charts/bind9
      #     ./cr index --owner $GITHUB_REPOSITORY_OWNER --git-repo HelmCharts --token $CR_TOKEN --index-path . --push
      #   env:
      #     CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.5.0
        env:
          CR_TOKEN: "${{ secrets.GH_TOKEN }}"
          CR_OWNER: $GITHUB_REPOSITORY_OWNER
